In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np


In [5]:
iris = load_iris()

In [8]:
LRscore = cross_val_score(LogisticRegression(), iris.data , iris.target) 
LRscore

C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [10]:
SVMscore = cross_val_score(SVC(), iris.data , iris.target) 
SVMscore

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
DTscore = cross_val_score(DecisionTreeClassifier(), iris.data , iris.target) 
DTscore

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [12]:

r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [13]:
np.average(r_scores)

0.9533333333333334

In [14]:
np.average(DTscore)

0.9533333333333334

In [15]:
np.average(SVMscore)

0.9666666666666666