In [14]:
from sklearn import svm , datasets 
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd
df = pd.DataFrame(iris.data , columns = iris.feature_names )
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(iris.data , iris.target , test_size = 0.2)

In [6]:
model = svm.SVC(kernel = 'rbf' , C = 30 , gamma = 'auto')
model.fit(X_train , y_train)
model.score(X_test , y_test)

0.9333333333333333

In [7]:
from sklearn.model_selection import cross_val_score

In [8]:
cross_val_score(svm.SVC(kernel = 'linear', C = 10 , gamma ='auto'), iris.data , iris.target , cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10 , gamma ='auto'), iris.data , iris.target , cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [10]:
cross_val_score(svm.SVC(kernel = 'linear', C = 20 , gamma ='auto'), iris.data , iris.target , cv = 5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [16]:
kernels = ['rbf','linear']
C = [1,10,20,30]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel = kval, C = cval , gamma ='auto'), iris.data , iris.target , cv = 5)
        avg_scores[kval+str(cval)] = np.average(cv_scores)
avg_scores

{'rbf1': 0.9800000000000001,
 'rbf10': 0.9800000000000001,
 'rbf20': 0.9666666666666668,
 'rbf30': 0.96,
 'linear1': 0.9800000000000001,
 'linear10': 0.9733333333333334,
 'linear20': 0.9666666666666666,
 'linear30': 0.96}

In [17]:
from sklearn.model_selection import GridSearchCV

In [21]:
clf = GridSearchCV(svm.SVC(gamma = 'auto'),
                  {
                      'C': [1,10,20],
                      'kernel':['rbf','linear']
                  } , cv = 5 , return_train_score = False )
clf.fit(iris.data , iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00388966, 0.00133114, 0.00149913, 0.00130019, 0.00088372,
        0.00020657]),
 'std_fit_time': array([0.00522131, 0.00037421, 0.00050228, 0.00084166, 0.00080774,
        0.00041313]),
 'mean_score_time': array([0.00142446, 0.0004015 , 0.00063457, 0.00067835, 0.00066261,
        0.00092344]),
 'std_score_time': array([0.00039319, 0.00049173, 0.00052036, 0.00055836, 0.00054946,
        0.00048419]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': ar

In [22]:
df = pd.DataFrame(clf.cv_results_)

In [23]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.003890      0.005221         0.001424        0.000393        1   
1       0.001331      0.000374         0.000401        0.000492        1   
2       0.001499      0.000502         0.000635        0.000520       10   
3       0.001300      0.000842         0.000678        0.000558       10   
4       0.000884      0.000808         0.000663        0.000549       20   
5       0.000207      0.000413         0.000923        0.000484       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6