In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [9]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size = 0.2 )

In [10]:
lr = LogisticRegression()
lr.fit(X_train , y_train)
lr.score(X_test,y_test)

C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [11]:
svm = SVC()
svm.fit(X_train ,y_train)
svm.score(X_test , y_test)

0.9861111111111112

In [12]:
rf = RandomForestClassifier(n_estimators = 40 ) #n = no of trees in forest
rf.fit(X_train , y_train)
rf.score(X_test , y_test)

0.9666666666666667

In [13]:
from sklearn.model_selection import KFold

In [14]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model , X_train , X_test , y_train , y_test):
    model.fit(X_train , y_train)
    return model.score(X_test , y_test)

In [17]:
get_score(LogisticRegression(),X_train , X_test , y_train , y_test)

C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [18]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [27]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data):
    X_train , X_test , y_train , y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index] , digits.target[test_index] 
    scores_lr.append(get_score(LogisticRegression(),X_train , X_test , y_train , y_test ))
    scores_svm.append(get_score(SVC(),X_train , X_test , y_train , y_test ))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 20),X_train , X_test , y_train , y_test ))




C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [28]:
scores_rf

[0.9148580968280468, 0.9482470784641068, 0.9048414023372288]

In [21]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [22]:
scores_lr


[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [29]:
from sklearn.model_selection import cross_val_score 


In [31]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])